# Generated by Django 2.2 on 2023-05-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(default=None, upload_to='images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Borrowing', to='api.Document'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='user_id_Borrowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Borrowing', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='breakdown_status',
            name='rack_id_Breakdown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Beakdown', to='api.Rack'),
        ),
        migrations.AlterField(
            model_name='document',
            name='rack_id_Document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Document', to='api.Rack'),
        ),
        migrations.AlterField(
            model_name='operation_status',
            name='rack_id_Operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operation', to='api.Rack'),
        ),
        migrations.AlterField(
            model_name='operation_status',
            name='user_id_Operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Opeation', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rack', to='api.Rack_group'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='user_id_Rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rack', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='rack_group',
            name='user_id_Rackgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rack_group', to='api.Account'),
        ),
    ]
