# Generated by Django 4.2.2 on 2023-06-23 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_history_maintenance_remove_document_draw_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
        migrations.AlterField(
            model_name='document',
            name='user_id_Document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.account'),
        ),
    ]
