# Generated by Django 4.2.2 on 2023-06-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_operation_handlemoving_alter_operation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='open_specific_rack',
            field=models.IntegerField(default=0),
        ),
    ]
