# Generated by Django 4.2.2 on 2023-06-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_operation_open_specific_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
