# Generated by Django 4.2.2 on 2023-06-29 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_operation_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='user_id_Borrowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Borrowing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='ventilate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operation_status',
            name='user_id_Operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rack',
            name='user_id_Rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rack', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rack_group',
            name='user_id_Rackgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rack_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
