# Generated by Django 4.2.2 on 2023-07-02 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_document_group_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='user_id_Rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rack', to=settings.AUTH_USER_MODEL),
        ),
    ]
