# Generated by Django 4.2.2 on 2023-07-02 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_rack_user_id_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack_group',
            name='user_id_Rackgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rack_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
