# Generated by Django 4.2.2 on 2023-07-04 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_rack_group_user_id_rackgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='user_id_Borrowing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Borrowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
